/// <reference types="vite/client" />

// Generated by scripts/vite-plugin-site.ts from the files in posts/.
declare module 'virtual:post-files' {
  // Post filenames (YYYY-MM-DD-slug.md), newest first.
  export const POST_FILES: readonly string[];
}
